[WIP] CBAPI-2202: Update Live Response
carbonblack/carbon-black-cloud-sdk-python pull request #156
Opened 2021-04-16 14:25 UTC by emitreva-cb

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Tests have been added that prove the fix is effective or that the feature works.
- [x] New and existing tests pass locally with the changes.
- [x] Code follows the style guidelines of this project (PEP8, clean code, linter).
- [x] A self-review of the code has been done.

## What is the ticket or issue number?
https://jira.carbonblack.local/browse/CBAPI-2202
https://jira.carbonblack.local/browse/CBAPI-2481
https://jira.carbonblack.local/browse/CBAPI-2485
https://jira.carbonblack.local/browse/CBAPI-2483

## Pull Request Description
- old Device model removed
- LR is now using v6 endpoints

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## How Has This Been Tested?
User tests

2021-04-19 21:11 UTC, avanbrunt-cb requested changes
The change overall looks create most of the requested changes are on naming conventions. We should also look into moving these example to the CBC SDK https://github.com/carbonblack/cbapi-python/tree/master/examples/defense/cblr

We will also need to test if the CBLR CLI tool still works and may make sense to make a Live Response folder instead of nesting the examples in a product folder. https://github.com/carbonblack/carbon-black-cloud-sdk-python/blob/develop/examples/endpoint_standard/live_response_cli.py

2021-04-19 21:11 UTC, avanbrunt-cb commented on src/tests/unit/test_live_response_api.py
> +    def respond_get2(url, query_parameters, default):
Apply in all locations

2021-04-20 05:46 UTC, emitreva-cb commented on src/tests/uat/live_response_api_uat.py
> +    lr_session.create_process(r'cmd.exe /c "ping.exe -t 192.168.1.1"',
Actually it doesn't really matter, if it doesn't exist (as it is indeed the case) we will still have a process, but will be timing out, but sure I will change that.

2021-04-20 13:24 UTC, emitreva-cb commented on src/tests/uat/live_response_api_uat.py
> +        print(f"profile being used is {args.__dict__}")
It might not be a profile, but other args so changing the text.

2021-04-20 13:24 UTC, emitreva-cb commented on src/cbc_sdk/live_response_api.py
> +        from cbc_sdk.platform import Device
Done.

2021-04-20 13:25 UTC, emitreva-cb commented on src/cbc_sdk/endpoint_standard/__init__.py
> +from cbc_sdk.endpoint_standard.base import Event, Policy, EnrichedEvent, Query, EnrichedEventQuery, \
Done.

2021-04-20 15:12 UTC, avanbrunt-cb commented on src/tests/uat/live_response_api_uat.py
> +        os.remove("test.txt")
Ignore this comment

2021-04-20 18:00 UTC, avanbrunt-cb approved these changes

2021-04-20 18:18 UTC, hkaragitliev-cb approved these changes

2021-04-20 18:56 UTC, merged