CBAPI-2552: Fix bugs in helpers.py and increase test coverage
carbonblack/carbon-black-cloud-sdk-python pull request #170
Opened 2021-05-12 13:18 UTC by emitreva-cb

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Tests have been added that prove the fix is effective or that the feature works.
- [x] New and existing tests pass locally with the changes.
- [x] Code follows the style guidelines of this project (PEP8, clean code, linter).
- [x] A self-review of the code has been done.

## What is the ticket or issue number?
https://jira.carbonblack.local/browse/CBAPI-2552

## Pull Request Description

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## How Has This Been Tested?

2021-05-12 13:22 UTC, emitreva-cb commented on src/cbc_sdk/helpers.py
> +def get_object_by_name_or_id(cb, cls, name_field="name", id=None, name='', force_init=True):
If name is not provided, then it fails to format it - attempted_to_find = "name {0:s}".format(name) and then fails with the error that  attempted_to_find is used before assignment.

2021-05-12 13:23 UTC, emitreva-cb commented on src/cbc_sdk/helpers.py
> -            objs = [cb.select(cls, id, force_init=force_init)]
As far as I saw NewBaseModel has force_init as parameter of the __init__, but not the classes that are inheriting that base class.

2021-05-12 15:04 UTC, avanbrunt-cb requested changes
Can we also remove `parser.add_argument("--window", help="Define search window", default='3d')` from `build_cli_parser` as this argument is not needed for every parser. We will need to add it to any example scripts which use it but that should be a small change

2021-05-12 15:08 UTC, avanbrunt-cb commented on src/cbc_sdk/helpers.py
>          else:
This function requires either an id or name we should through an error neither are provided. I would leave the `name=None` then convert the if else to an if elif else where the else raises an Exception indicating that either id or name should be provided. We should also consider the case where both are provided, do we want to fetch by id then verify if the name matches or raise an error before making an API request indicating only one can be specified

2021-05-12 17:14 UTC, avanbrunt-cb approved these changes
Thanks! Looks good

2021-05-13 06:58 UTC, hkaragitliev-cb approved these changes
LGTM

2021-05-13 07:01 UTC, merged