CBAPI-3539: Update SDK to use watchlist manager v3 instead of v2 APIs
carbonblack/carbon-black-cloud-sdk-python pull request #273
Opened 2022-02-22 20:03 UTC by abowersox-cb

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Tests have been added that prove the fix is effective or that the feature works.
- [x] New and existing tests pass locally with the changes.
- [x] Code follows the style guidelines of this project (PEP8, clean code, linter).
- [x] A self-review of the code has been done.

## What is the ticket or issue number?

https://jira.carbonblack.local/browse/CBAPI-3539

## Pull Request Description

Replaces the v2 Watchlist APIs with v3 APIs, which includes ensuring that the org key is properly formatted into the URIs whenever necessary.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## How Has This Been Tested?

Unit tests have been adjusted to reflect the changes.  No net loss of coverage as a result.

2022-02-22 21:43 UTC, avanbrunt-cb requested changes
I'd like to see a UAT test created before I approve

2022-02-23 21:29 UTC, abowersox-cb commented
Added in most recent commit.

2022-02-23 21:34 UTC, avanbrunt-cb approved these changes

2022-02-24 17:53 UTC, kebringer-cb approved these changes

2022-02-24 19:39 UTC, merged