CBAPI-4437: Upgraded pymox to 1.0.0
carbonblack/carbon-black-cloud-sdk-python pull request #357
Opened 2023-05-17 18:23 UTC by abowersox-cb

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Tests have been added that prove the fix is effective or that the feature works.
- [x] New and existing tests pass locally with the changes.
- [ ] Code follows the style guidelines of this project (PEP8, clean code, linter).
- [x] A self-review of the code has been done.

## What is the ticket or issue number?

https://jira.carbonblack.local/browse/CBAPI-4437

## Pull Request Description

Upgrade the "pinned" version of pymox in `requirements.txt` to 1.0.0.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## How Has This Been Tested?

Complete pytest run done; finishes successfully with no warning messages.

2023-05-17 19:05 UTC, avanbrunt-cb approved these changes

2023-05-17 19:06 UTC, avanbrunt-cb requested changes
Don't forget setup.py

2023-05-17 21:32 UTC, avanbrunt-cb approved these changes

2023-05-18 12:30 UTC, emitreva-cb approved these changes

2023-05-18 13:18 UTC, merged