added function set_time_criterion_filters which has the same function…
carbonblack/carbon-black-cloud-sdk-python pull request #406
Opened 2023-09-21 17:00 UTC by heiderje-vmware

…ality as the legacy set_time_range. AlertsSearchQuery.set_time_range now sets the overall timerange if no field name is used, or if a field name is used adds to the criterion for the field for v6 backwards compatibility

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Tests have been added that prove the fix is effective or that the feature works.
- [x] New and existing tests pass locally with the changes.
- [x] Code follows the style guidelines of this project (PEP8, clean code, linter).
- [x] A self-review of the code has been done.

## What is the ticket or issue number?
[CBAPI-4979: V7 Set Time Range](https://jira.carbonblack.local/browse/CBAPI-4979)

## Pull Request Description

This implements the global time range feature added in the v7 api via set_time_range method on the AlertSearchQuery class. also added to the AlertSearchQuery class is set_time_criterion_filter, which handles setting a time range on a criterion field, it is a copy of set_time_range from legacy. The set_time_range method essentially implements the base set_time_range but if the first argument is an criterion field calls the set_time_criterion_filter method. this can be removed after v6 is deprecated

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## How Has This Been Tested?

manual testing with debugger and unit tests

2023-09-21 17:54 UTC, avanbrunt-cb commented on src/cbc_sdk/platform/alerts.py
> +    def set_time_range(self, *args, **kwargs):
Should we remove `set_time_range` from https://github.com/carbonblack/carbon-black-cloud-sdk-python/blob/Alerts_v7_SDK_Changes/src/cbc_sdk/platform/legacy_alerts.py#L342 as these conflict on the Alert Query class

2023-09-21 20:04 UTC, avanbrunt-cb commented on src/cbc_sdk/platform/alerts.py
> +            if key not in ["create_time", "first_event_time", "last_event_time", "last_update_time",
If we set `backend_timestamp` or `create_time` we should probably also set `_time_range` on top of the criteria as they would need to modify both

2023-09-21 20:04 UTC, avanbrunt-cb commented on src/cbc_sdk/platform/alerts.py
> +                if not isinstance(start, str):
Should we perform an ISO 8601 timestamp check

2023-09-21 20:05 UTC, avanbrunt-cb commented on src/cbc_sdk/platform/alerts.py
> +                if not isinstance(start, str):
stime.isoformat()

2023-09-21 20:20 UTC, kebringer-cb commented on src/cbc_sdk/platform/alerts.py
> +            raise ApiError("key must be one of create_time, first_event_time, last_event_time, backend_timestamp,"
Valid fields for v7 are:
backend_timestamp
backend_update_timestamp
detection_timestamp
first_event_timestamp
last_event_timestamp
mdr_determination_change_timestamp
mdr_workflow_change_timestamp
user_update_timestamp
workflow_change_timestamp

2023-09-21 20:39 UTC, kebringer-cb commented on src/cbc_sdk/platform/alerts.py
> +    def set_time_criterion_filter(self, key, **kwargs):
The other criteria are added with ` add_criteria(key, newlist)`
So this could be a better name  `add_time_criteria(key, **kwargs)`

2023-09-26 18:48 UTC, avanbrunt-cb approved these changes

2023-09-26 19:24 UTC, avanbrunt-cb requested changes
There is no v7 alerts test for set_time_range with no key specified

2023-09-26 19:33 UTC, kebringer-cb commented on src/cbc_sdk/platform/alerts.py
> +                self.add_time_criteria(key, **kwargs)
key needs to be converted from v6 field name to v7.
Would like to see a mock test for this that validates the post request.

This python snippet:
alert_list = cb.select(Alert).set_time_range("first_event_time", start="2023-09-19T01:00:00.000", end="2023-09-20T01:00:00.000")

should generate this request.  (rows, start are set in base.  Get latest off the parent branch to remove the empty query element):
{
    "criteria": {
        "first_event_timestamp": {
            "end": "2023-09-20T01:00:00.000Z",
            "start": "2023-09-19T01:00:00.000Z"
        }
    },
    "rows": 100,
    "start": 1
}

2023-09-26 19:33 UTC, kebringer-cb commented on src/cbc_sdk/platform/alerts.py
> +    def _is_valid_time_criteria_key(self, key):
Need a different version of this method to be used at line 1043 when supporting the backwards compatibility of set_time_range, and has the fields that are valid for v6 legacy compatibility.

This method with the v7 valid fields should be called in add_time_criteria()

2023-09-26 19:33 UTC, kebringer-cb commented on src/cbc_sdk/platform/alerts.py
> +                    time_filter = {"start": stime.isoformat(), "end": etime.isoformat()}
needs time format to be updated.

2023-09-27 16:57 UTC, kebringer-cb commented on src/cbc_sdk/platform/alerts.py
> +            >>> query = api.select(Event).set_time_range(start="2020-10-20T20:34:07Z")
Still needs an update - will review docs holistically when all changes are complete.  Other sections need updates too.

2023-09-27 17:26 UTC, avanbrunt-cb approved these changes

2023-09-30 21:43 UTC, kebringer-cb approved these changes

2023-10-02 16:58 UTC, merged