1. Added support for collapse field parameter for process search job
carbonblack/carbon-black-cloud-sdk-python pull request #502
Opened 2024-04-23 08:44 UTC by vsvvj-cb

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Tests have been added that prove the fix is effective or that the feature works.
- [ ] New and existing tests pass locally with the changes.
- [ ] Code follows the style guidelines of this project (PEP8, clean code, linter).
- [ ] A self-review of the code has been done.

## What is the ticket or issue number?
https://jira.carbonblack.local/browse/PRDTEST-15265

## Pull Request Description
An additional support is added for collapse_field parameter in payload for process search job API.

## Does this introduce a breaking change?

- [ ] Yes
- [x ] No

## How Has This Been Tested?

2024-04-23 13:48 UTC, avanbrunt-cb requested changes
Please add a test case which covers this new function. It can follow similar to the following test https://github.com/carbonblack/carbon-black-cloud-sdk-python/blob/develop/src/tests/unit/platform/test_platform_process.py#L747

2024-04-24 12:25 UTC, vsvvj-cb commented
Added unit test case

> Please add a test case which covers this new function. It can follow similar to the following test https://github.com/carbonblack/carbon-black-cloud-sdk-python/blob/develop/src/tests/unit/platform/test_platform_process.py#L747

Added unit test case for this function.

2024-04-25 16:26 UTC, avanbrunt-cb approved these changes

2024-04-25 16:44 UTC, abowersox-cb approved these changes

2024-04-26 19:25 UTC, merged